config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/info' => 'static_pages#info', as: :info
  get '/safety' => 'static_pages#safety', as: :safety
  get '/maps' => 'static_pages#maps', as: :maps
  get '/action' => 'static_pages#action', as: :action

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def info
  end

  def action
  end

  def maps

  end

  def safety
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIKE LA"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
      <ul>
        <li class="footer" id="footer">Bike LA | Bike Safely throughout Los Angeles, CA</li>
        <li class="footer">About Us</li>
        <li class="footer">Contact</li>
        <li class="footer">FAQS</li>
        <li class="footer">California Transportation Act</li>
        <li class="footer-icons"><%= link_to "http://facebook.com", :target => "_blank" do%><i class="fa fa-facebook"></i></li><% end %>
        <li class="footer-icons"><%= link_to "http://twitter.com", :target => "_blank" do%><i class="fa fa-twitter"></i></li><% end %>
        <li class="footer-icons"><%= link_to "http://pinterest.com", :target => "_blank" do%><i class="fa fa-pinterest"></i></li><% end %>
        <li class="footer-icons"><%= link_to "http://instagram.com", :target => "_blank" do%><i class="fa fa-instagram"></i></li><% end %>
      </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-fixed-top navbar-inverse " role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-fixed-top">
      <li id = "logo"><%= link_to image_tag("logo.png"), root_path%></li>
      <li class="space-nav"><%= link_to "INFORMATION", info_path %></li>
      <li class="space-nav"><%= link_to "SAFETY", safety_path %></li>
      <li class="space-nav"><%= link_to "GETTING AROUND", maps_path %></li>
      <li class="space-nav"><%= link_to "GETTING INVOLVED", action_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- FAVICON -->
  <%= favicon_link_tag 'http://icons.iconarchive.com/icons/iconsmind/outline/512/Bicycle-icon.png' %>
  <!-- GOOGLEFONTS -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Domine:400,700' rel='stylesheet' type='text/css'>
  <!-- FONTAWESOME ICONS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!-- BOOTSTRAP -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"> </script>
  <title>BikeLa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="/vendor/assets/javascripts/parallax/parallax.js"></script>
</head>
<body id="bootstrap-overrides">
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/action.html.erb
<h3>Coming Soon!</h3>
<div class="container">
<p>&nbsp;</p>
<p>Our next step is to include additional functionality to empower cyclists like you to build a bigger, better cycling community.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>

app/views/static_pages/home.html.erb
<div class="image">
<%= image_tag("hero.jpg") %>
<h1>Increasing the number of bike commuters in Los Angeles<br> would ease the city's notorious traffic,<br> cut down on fossil fuel dependence, and get residents exercising.</h1>
</div>
<div>
&nbsp;
</div>
<div class="image">
<%= image_tag("home1.jpg") %>
<h2><%= link_to "information", info_path %></h2>
</div>
<div class="image">
<%= image_tag("home3.jpg") %>
<h2><%= link_to "safety", safety_path %></h2>
</div>
<div class="image">
<%= image_tag("home2.jpg") %>
<h2><%= link_to "getting around", maps_path %></h2>
</div>
<div class="image">
<%= image_tag("home4.jpg") %>
<h2><%= link_to "getting involved", action_path %></h2>
</div>
<!-- <div class="parallax-window" data-parallax="scroll" data-image-src="images/home1.jpg"></div>
<div class="parallax-window" data-parallax="scroll" data-image-src="images/home2.jpg"></div>
<div class="parallax-window" data-parallax="scroll" data-image-src="images/home1.jpg"></div>
<div class="parallax-window" data-parallax="scroll" data-image-src="images/home2.jpg"></div> -->

app/views/static_pages/info.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 page-image"><%= image_tag("pollution.png") %></div>
    <div class="col-md-8">
      <h3>Pollution</h3>
      <p>The LA area has the nations worst ozone pollution.</p>
      <p>30 million people live in areas with chronic levels of pollution.</p>
      <p>LA violates federal health standards 137 days per year.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h3>Health + Fitness</h3>
      <p>Exercise is like fertilizer for your brain.</p>
      <p>Cycling elevates your mood.</p>
      <p>Cycling is good for your heart + soul.</p>
    </div>
    <div class="col-md-4 page-image"><%= image_tag("health.png") %></div>
  </div>
  <div class="row">
    <div class="col-md-4 page-image"><%= image_tag("traffic.png") %></div>
    <div class="col-md-8">
      <h3>Reduce Traffic</h3>
      <p>Angelinos drive on average 23 miles per day.</p>
      <p>We spend more time in traffic than anyone else in the US.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h3>Build Community</h3>
      <p>Cyclists form strong communities.</p>
      <p>Communities with cyclists are happier.</p>
    </div>
    <div class="col-md-4 page-image"><%= image_tag("community.png") %></div>
  </div>
</div>

app/views/static_pages/maps.html.erb
<div id="maps-body">
  <div id="search-container">
    <form id="search">
      <input placeholder="Search by Zip"></input>
      <div id="search-btn"></div>
    </form>
  </div>
  <div id="googleMap">
  </div>
  <div id="content">

    <div id="filters" class="col-lg-6">
      <div class="row">
        <div class="col-md-3">
          <span class="map-header">FILTERS: </span>
        </div>
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control" aria-label="Text input with dropdown button">
            <div class="input-group-btn">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-angle-down"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Echo Park</a>
                <a class="dropdown-item" href="#">Silver Lake</a>
                <a class="dropdown-item" href="#">Financial District</a>
                <div role="separator" class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="input-group">
            <span class="input-group-addon">
              <input type="checkbox" aria-label="Checkbox for following text input">
            </span>
            <input placeholder="Existing Bikeways" type="text" class="form-control" aria-label="Text input with checkbox">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="input-group">
            <span class="input-group-addon">
              <input type="checkbox" aria-label="Checkbox for following text input">
            </span>
            <input placeholder="In Development" type="text" class="form-control" aria-label="Text input with checkbox">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="input-group">
            <span class="input-group-addon">
              <input type="checkbox" aria-label="Checkbox for following text input">
            </span>
            <input placeholder="Bike Parking" type="text" class="form-control" aria-label="Text input with checkbox">
          </div>
        </div>
      </div>
    </div>

  <div id="route-info" class="col-lg-6">
      <div class="row">
        <div class="col-md-12">
          <span class='map-header'>ROUTE DETAILS: </span>
        </div>
      </div>
  </div>
</div>

app/views/static_pages/safety.html.erb
<div class="container">
 <div class="row">
    <div class="col-md-8">
      <h3>Wear a Helmet</h3>
      <p>Wear a helmet whenever you ride.</p>
      <p>Wear light colored clothes at night.</p>
      <p>Dressing in layers allows you to adjust to temperatures on longer rides.</p>
    </div>
    <div class="col-md-4 page-image"><%= image_tag("helmet.png") %></div>
  </div>
  <div class="row">
    <div class="col-md-4 page-image"><%= image_tag("signals.png") %></div>
    <div class="col-md-8">
      <h3>Use Hand Signals</h3>
      <p>Use hand signals to tell motorists what you intend to do.</p>
      <p>It is safer to tell a driver your intended direction than to assume they know.</p>
      <p>Signaling is a matter of law, courtesy, and self-protection.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h3>Obey All Traffic Laws</h3>
      <p>Stop at all stop signs and signals as required by law.</p>
      <p>Ride in the same direction as automobile traffic.</p>
      <p>Bicycles have legal access to the roadway and must obey all traffic signs.</p>
    </div>
    <div class="col-md-4 page-image"><%= image_tag("laws.png") %></div>
  </div>
  <div class="row">
    <div class="col-md-4 page-image"><%= image_tag("lights.png") %></div>
    <div class="col-md-8">
      <h3>Use Front + Rear Lights</h3>
      <p>Be sure your bike is adjusted to fit you properly.</p>
      <p>Use bells, rear view mirrors, fenders, and racks.</p>
      <p>Use a strong headlight and tail light at night.</p>
    </div>
  </div>
</div>